### ISSUE TITLE
Bagaimana mencari data sekolah berdasarkan provinsi?

### ISSUE THREAD

**Issue by aliarsa48** [wanrabbae/api-sekolah-indonesia#1]
Saya sudah coba 
https://api-sekolah-indonesia.herokuapp.com/sekolah/s?kode_prop=160000
dan
https://api-sekolah-indonesia.herokuapp.com/sekolah/s?propinsi=Prov. Kalimantan Timur
tapi tidak bisa

**Comment by wanrabbae** [comment]
Untuk saat ini, mencari data sekolah hanya berdasarkan nama sekolah kak ☺️🙏

Kedepannya API ini akan dikembangkan lagi.

**Comment by aliarsa48** [comment]
> Untuk saat ini, mencari data sekolah hanya berdasarkan nama sekolah kak ☺️🙏
> 
> Kedepannya API ini akan dikembangkan lagi.

baiklah, terima kasih kak 🙏
