### ISSUE TITLE
Penambahan SMK TELKOM MALANG

### ISSUE THREAD

**Issue by yUm1k4** [wanrabbae/api-sekolah-indonesia#3]
Halo min, ingin melaporkan bahwa SMK TELKOM MALANG belum terdaftar https://www.smktelkom-mlg.sch.id/

Terimakasih.

**Comment by wanrabbae** [comment]
Baik terimakasih atas laporanya, nnti akan saya tambahkan yah.
Apa kk pnya data dari smk tersebut ? seperti kode_prop, propinsi, npsn dll.

**Comment by wanrabbae** [comment]
> Halo min, ingin melaporkan bahwa SMK TELKOM MALANG belum terdaftar https://www.smktelkom-mlg.sch.id/
> 
> Terimakasih.

SMK TELKOM MALANG ada kok kak namun atas nama SMKS TELKOM SANDHY PUTRA dengan alamat JL. DANAU RANAU NO.01 betul ?
