### ISSUE TITLE
Pencarian sekolah khusus tingkat atas dan  pencarian menggunakan npsn

### ISSUE THREAD

**Issue by vanrezky** [wanrabbae/api-sekolah-indonesia#5]
halo terimakasih telah membuat API ini dan ini sangat membantu saya.
tetapi ada kendala yang saya hadapi, yaitu :
1. filter sekolah yang hanya tinggat atas (sma/smk).
2. pencarian menggunakan npsn

terimakasih salam.

**Comment by wanrabbae** [comment]
untuk pencarian berdasarkan npsn done ya

```bash
/sekolah?npsn=20106342
```
untuk filter sekolah berdasarkan tingkat / jenjang sudah ada ya bisa dicek lagi
